apiVersion: kubeovn.io/v1
kind: ProviderNetwork
metadata:
  name: provider
spec:
  defaultInterface: bond0
  excludeNodes:
  - 10.10.158.11-node
  - 10.10.95.11-master
  - 10.10.95.12-node
  - 10.10.95.13-node
  - 10.10.95.14-node

---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ovn
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "kube-ovn",
      "server_socket": "/run/openvswitch/kube-ovn-daemon.sock",
      "provider": "ovn.default.ovn"
    }'
--- 
apiVersion: kubeovn.io/v1
kind: Vlan
metadata:
  creationTimestamp: "2023-07-05T14:09:01Z"
  generation: 1
  name: vlan96
  resourceVersion: "284035130"
  uid: f43a1366-99bb-4f66-ad1d-9d3d08d8c71a
spec:
  id: 96
  provider: provider
status:
  subnets:
  - subnet1
---
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: subnet1
spec:
  cidrBlock: 10.10.96.0/24
  default: false
  disableGatewayCheck: true
  excludeIps:
  - 10.10.96.1..10.10.96.3
  - 10.10.96.250..10.10.96.254
  gateway: 10.10.96.254
  gatewayNode: ""
  gatewayType: distributed
  natOutgoing: false
  private: false
  provider: ovn.default.ovn
  protocol: IPv4
  vlan: vlan96

